FROM eclipse-temurin:17-jdk as build
WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ./mvnw install -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /workspace/app/target/paypal-java-mcp-server-0.0.1-SNAPSHOT-stdio.jar /app/app.jar

# Create a log directory
RUN mkdir -p /app/logs

# Set environment variables
ENV SPRING_PROFILES_ACTIVE=stdio
ENV LOGGING_FILE_NAME=/app/logs/mcp-server.log

ENTRYPOINT ["java","-jar","/app/app.jar"] 